[package]
name = "road"
version = "0.1.0"
authors = ["dmalyshau"]

[dependencies]
byteorder = "0.5"
cgmath = "0.10"
env_logger = "0.3"
getopts = "0.2"
gfx = "0.12"
gfx_window_glutin = "0.12"
glutin = "0.6"
log = "0.3"
progressive = "0.1"
rust-ini = "0.9"
rustc-serialize = "0.3"
time = "0.1"
toml = "0.1"
