[package]
name = "road"
version = "0.1.0"
authors = ["dmalyshau"]

[dependencies]
byteorder = "0.5"
cgmath = "0.10"
env_logger = "0.3"
gfx = "0.11"
gfx_window_glutin = "0.11"
glutin = "0.5"
log = "0.3"
progressive = "0.1"
rust-ini = "0.9"
rustc-serialize = "0.3"
toml = "0.1"
