data_path = "/opt/gog/Vangers/game"

[game]
level = "fostral"

[car]
id = "OxidizeMonk"
slots = []
#id = "IronShadow"
#slots = ["HeavyLaser", "LightMissile", "LightFireBall"]

[window]
title = "Rusty Road"
size = [1280, 800]
